package_path: "/home/cnrismn/git_workspace/GrapheNet"
spath: "${package_path}/data/subset_png"
dpath: "${package_path}/data/training_dataset/" #"/home/cnrismn/git_workspace/Graphene/data/subset_training_dataset/"
path_xyz: "${package_path}/data/subset_xyz/"
path_csv: "${path_xyz}/dataset.csv"
plot_distributions: True
features: ["total_energy"]

randomly:
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  shuffle: True

from_csv:
  flag: False
  csv_dataset_path: ""
