data_folder: data
dataset_name: training_dataset
dataset_csv_path: ~/xyz_files_GO/dataset_with_formation_energy.csv
features:
  [
    "ionization_potential",
    "electron_affinity",
    "electronegativity",
    "Fermi_energy",
    "formation_energy",
  ]
plot_distributions: True
augmented_png: false
augmented_xyz: false

randomly:
  n_items: 7000
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  oxygen_outliers_th: 0.2
  min_num_atoms: 0

from_dataset:
  dataset_path:
