package_path: "/home/cnrismn/git_workspace/GrapheNet"
data_path: "${package_path}/data_GO"
path_xyz: "${data_path}/xyz_files/"
path_csv: "${path_xyz}/dataset.csv"
spath: "${data_path}/png_files"
dpath: "${data_path}/training_dataset/"
plot_distributions: True
features: ["ionization_potential", "electron_affinity", "electronegativity", "Fermi_energy", "total_energy"]
target: None

randomly:
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  shuffle: True
  oxygen_outliers_th: 0.2

from_csv:
  flag: False
  csv_dataset_path: ""
