package_path: "/home/cnrismn/git_workspace/GrapheNet"
data_path: "${package_path}/UMAP/cluster0_1_5_8_9_11_12_14_15_22"
stock_csv_path: "/home/cnrismn/git_workspace/Chemception/data/xyz_files_opt/dataset_complete.csv"
path_xyz: "${data_path}/xyz_files/"
path_csv: "${path_xyz}/dataset.csv"
spath: "${data_path}/png_files"
dpath: "${data_path}/training_dataset/"
plot_distributions: True
features:
  [
    "ionization_potential",
    "electron_affinity",
    "electronegativity",
    "Fermi_energy",
    "total_energy",
  ]
target: None

randomly:
  n_items: 7000
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  shuffle: True
  oxygen_outliers_th: 0.2
  min_num_atoms: 0
  drop_custom: True

from_csv:
  csv_dataset_path: "/home/cnrismn/git_workspace/GrapheNet/UMAP/dataset_umap.csv"
