package_path: "/home/tommaso/git_workspace/GrapheNet"
data_path: "${package_path}/data_GO"
stock_csv_path: "/home/tommaso/xyz_files_GO/dataset_with_formation_energy.csv"
path_xyz: "${data_path}/xyz_files/"
path_csv: "${path_xyz}/dataset.csv"
spath: "${data_path}/png_files"
dpath: "${data_path}/training_dataset_reference/"
plot_distributions: True
features:
  [
    "ionization_potential",
    "electron_affinity",
    "electronegativity",
    "Fermi_energy",
    "formation_energy",
  ]
augmented: false

randomly:
  n_items: 7000
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  shuffle: True
  oxygen_outliers_th: 0.2
  min_num_atoms: 0
  drop_custom: True

from_csv:
  csv_dataset_path: "/home/tommaso/git_workspace/GrapheNet/data_GO/training_dataset/dataset.csv"
