# PATHS
package_path: /home/tommaso/git_workspace/GrapheNet

dataset_path: ${package_path}/data_final/Coulomb_GO/cluster_310-350/training_dataset
#dpath: ${dataset_path}/matrices_KRR
dpath: /home/tommaso/git_workspace/prova/${model}
resolution: 350
target_list:
  [
    "Fermi_energy",
    "electron_affinity",
    "electronegativity",
    "formation_energy",
    "ionization_potential",
  ]
model: XGBoost #XGBoost, LinearRegression or KRR
eigenvalues: false

# SLURM
slurm_job_name: KRR_GrapheNet
slurm_mem:
slurm_ncpus: 16
slurm_ngpus: 1
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude: gn05,gn06,gn07

# VERBOSITY
verbose: True
