atom_types: 3
cluster: true
cluster_num_workers: 8
coulomb: false
deterministic: true
enlargement_method: padding
num_workers: 6
package_path: /home/tommaso/git_workspace/GrapheNet
resolution: 160
sample: /home/tommaso/git_workspace/GrapheNet/featuremaps_visualization/neutral_1021/neutral_1021.png
target: ionization_potential
train:
  base_lr: 0.0
  batch_size: 32
  compile: false
  dpath: ${train.spath}/models/${target}
  lr_list:
    Fermi_energy: 0.058841390814253124
    electron_affinity: 0.0428044113914066
    electronegativity: 0.04550807817481413
    formation_energy: 0.20911237334180677
    ionization_potential: 0.015186596128617183
  matmul_precision: high
  num_epochs: 150
  spath: ${package_path}/data_GO/training_dataset_xyz_augmented
