name: train_predict_coulomb_GO
atom_types: 3
cluster: true
coulomb: true
deterministic: true
num_workers: 8
enlargement_method: padding
resolution: 1950
target: electron_affinity
train:
  base_lr: 0.0428044113914066
  batch_size: 4
  compile: false
  lr_list:
    Fermi_energy: 0.058841390814253124
    electron_affinity: 0.0428044113914066
    electronegativity: 0.04550807817481413
    formation_energy: 0.20911237334180677
    ionization_potential: 0.015186596128617183
  matmul_precision: high
  num_epochs: 150
  dataset_path: data/Coulomb_GO/training_dataset
