package_path: "/home/cnrismn/git_workspace/GrapheNet"
target: "total_energy"
resolution: 96
normalize: None  #"normalization" | "z_score" | "log_scaling" | None
cluster: False
num_workers: 6
cluster_num_workers: 16
atom_types: 1
sample: None


train:
  spath: "${package_path}/data_G/training_dataset"
  base_lr: 0.007148138391360274 #0.008712970230331395 #0.009004782855993668 #0.0009770215402745278 #trovato con hp_finder sul nuovo dataset da 7000 samples
  num_epochs: 150
  step_size_lr: 65
  batch_size: 32
