package_path: "/home/cnrismn/git_workspace/GrapheNet"
target: "total_energy"
resolution: 160
normalize: None  #"normalization" | "z_score" | "log_scaling" | None
cluster: False
num_workers: 6
cluster_num_workers: 16
atom_types: 1


train:
  spath: "${package_path}/data/training_dataset"
  base_lr: 0.0008700623594429155 #trovato con hp_finder sul nuovo dataset da 7000 samples
  num_epochs: 150
  step_size_lr: 65
  batch_size: 32
