atom_types: 3
cluster: false
cluster_num_workers: 8
coulomb: false
deterministic: true
enlargement_method: padding
normalize: None
num_workers: 6
package_path: /home/cnrismn/git_workspace/GrapheNet
resolution: 145
sample: /home/cnrismn/git_workspace/GrapheNet/dftb/neutral_1021/neutral_1021.png
target: electron_affinity
train:
  base_lr: 0.061813296683228255
  batch_size: 64
  dpath: ${train.spath}/models/${target}
  lr_list:
    Fermi_energy: 0.09653253233375945
    electron_affinity: 0.061813296683228255
    electronegativity: 0.04048360377132749
    ionization_potential: 0.02133368544635407
    total_energy: 0.014135120055669028
  num_epochs: 150
  spath: ${package_path}/data_GO_EA_threshold_5.7/training_dataset
