atom_types: 3
cluster: false
cluster_num_workers: 8
coulomb: false
deterministic: true
enlargement_method: padding
kfold: false
num_workers: 6
package_path: /home/tom/git_workspace/tesi/GrapheNet
resolution: 145
target: Fermi_energy
train:
  base_lr: 0.01
  batch_size: 32
  compile: false
  dpath: ${train.spath}/models_${train.network}/${target}
  matmul_precision: high
  num_epochs: 150
  spath: ${package_path}/data/png_training_dataset_reference
  grayscale: false
  network: InceptionResNet #CNN, InceptionResNet or Resnet18 or E2InceptionResNet

# SLURM
slurm_job_name: Images_GrapheNet
slurm_mem:
slurm_ncpus: 16
slurm_ngpus: 1
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude: gn05,gn06,gn07,gn03,gn04,gn02

# VERBOSITY
verbose: false
