atom_types: 3
cluster: false
cluster_num_workers: 8
coulomb: false
deterministic: true
enlargement_method: padding
normalize: None
num_workers: 6
package_path: /home/cnrismn/git_workspace/GrapheNet
resolution: 160
sample: /home/cnrismn/git_workspace/GrapheNet/dftb/neutral_1021/neutral_1021.png
target: ionization_potential
train:
  base_lr: 0.007977032186834113
  batch_size: 32
  dpath: ${train.spath}/models/${target}
  num_epochs: 150
  spath: ${package_path}/data_GO/training_dataset
