atom_types: 3
cluster: false
cluster_num_workers: 8
enlargement_method: padding
normalize: None
num_workers: 6
package_path: /home/cnrismn/git_workspace/GrapheNet
resolution: 160
sample: None
target: ionization_potential
train:
  base_lr: 0.03384544651174149
  batch_size: 32
  dpath: ${train.spath}/models_with_distribution/${target}
  num_epochs: 150
  spath: ${package_path}/data_GO/custom_training_dataset
