atom_types: 3
cluster: true
cluster_num_workers: 8
coulomb: true
deterministic: true
kfold: false
enlargement_method: padding
num_workers: 6
package_path: /home/tommaso/git_workspace/GrapheNet
resolution: 660
sample: /home/tommaso/git_workspace/GrapheNet/dftb/neutral_1021/neutral_1021.png
target: electron_affinity
train:
  base_lr: 0.0428044113914066
  batch_size: 32
  compile: false
  dpath: ${train.spath}/matrices_models_norm_padd_max_${train.network}/${target}
  lr_list:
    Fermi_energy: 0.01 #0.058841390814253124
    electron_affinity: 0.01 #0.0428044113914066
    electronegativity: 0.01 #0.04550807817481413
    formation_energy: 0.01 #0.20911237334180677
    ionization_potential: 0.01 #0.015186596128617183
    #total_energy: 0.014125999813258398 #0.014125999813258398 for GO and 0.1368859516416597 for G
    #energy_per_atom: 0.06555071644078239
  matmul_precision: high
  num_epochs: 150
  spath: ${package_path}/data_final/Coulomb_GO/cluster_310-660/training_dataset
  grayscale: false
  network: InceptionResNet #CNN, InceptionResNet or Resnet18

# SLURM
slurm_job_name: Coulomb_GrapheNet
slurm_mem:
slurm_ncpus: 16
slurm_ngpus: 1
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude: gn05,gn06,gn07

# VERBOSITY
verbose: True
